import "./globals.css";
import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import { BottomNavigation } from "@/components/BottomNavigation";

const inter = Open_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <BottomNavigation />
        {children}
        <BottomNavigation />
      </body>
    </html>
  );
}
